name: flutterfirebaseauth
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.4
  google_sign_in: ^4.5.4
  flutter_facebook_login: ^3.0.0
  intl: ^0.16.1
  uuid: ^2.0.0
  cool_alert: ^1.0.1
  cupertino_icons: ^0.1.3
  ff_navigation_bar: ^0.1.5
  carousel_slider: ^1.3.0
  sliding_up_panel: ^1.0.2
  http: ^0.12.0+1
  json_serializable: ^3.3.0
  # flutter_polyline_points: ^0.1.0
  google_maps_flutter : ^1.0.6
  google_maps_place_picker : ^1.0.0
  geolocator: ^6.1.4+1
  google_maps_webservice : ^0.0.18
  tuple : ^1.0.3
  permission : ^0.1.7
  shortuuid : ^2.1.1
  shifting_tabbar: ^0.3.1
  place_picker : ^0.9.16
  latlong: ^0.6.1
  shared_preferences: ^0.5.12
  flutter_slidable: ^0.5.7
  cloud_firestore:  ^0.13.7
  firebase_storage: ^3.1.6
  fluttertoast: ^7.1.1
  cached_network_image: ^2.2.0+1
  firebase_messaging: ^6.0.16
  photo_view: ^0.10.0
  firebase_dynamic_links: ^0.5.1
  image_picker: ^0.6.7+11
  flutter_local_notifications: ^1.4.4+4
  expansion_card: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0
flutter:

  uses-material-design: true

  assets:
    - assets/car.PNG
    - assets/delivery.PNG
    - assets/food.PNG
    - assets/mart.PNG
    - assets/motor.png
    - assets/reward.PNG
    - assets/splash.png
    - assets/promo1.jpg
    - assets/promo.jpg
    - assets/promo2.jpg
    - assets/promo3.jpg
    - assets/promo4.jpg
    - assets/promo5.jpg
    - assets/slider/promo2.jpg
    - assets/slider/promo3.jpg
    - assets/slider/promo4.jpg
    - assets/slider/promo5.jpg
    - assets/profile/as.png
    - assets/profile/email_icon.png
    - assets/profile/logo.png
    - assets/profile/password_icon.png
    - assets/profile/powered_by.png
    - assets/profile/user_icon.png
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
